# Generated by Django 2.1.2 on 2018-10-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20181024_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='public',
        ),
    ]
