# Generated by Django 2.1.2 on 2018-10-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_topic_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_hide',
            field=models.BooleanField(default=False),
        ),
    ]
