# Generated by Django 2.1.2 on 2018-10-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_entry_entry_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_hide',
            field=models.BooleanField(default=False),
        ),
    ]
