# Generated by Django 2.1.2 on 2018-11-02 06:45

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
